import{a as u,S as p,i as a}from"./assets/vendor-C3hA4BqS.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d="55520229-6b38dd18315a985816c1e4a23",m="https://pixabay.com/api/";function f(s){return u(m,{params:{key:d,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:n})=>n)}const i=document.querySelector(".gallery"),c=document.querySelector(".loader"),y=new p(".gallery-item a",{captionDelay:1e3,captionsData:"alt"});function g(s){const n=s.map(t=>`
          <li class="gallery-item">
          <a class="gallery-thumb" href="${t.largeImageURL}"><img class="gallery-img" src="${t.webformatURL}" alt="${t.name||t.tags}" /></a>
          <ul class="gallery-content-list">
            <li class="gallery-content-item"><span>Likes</span><span>${t.likes}</span></li>
            <li class="gallery-content-item"><span>Views</span><span>${t.views}</span></li>
            <li class="gallery-content-item"><span>Comments</span><span>${t.comments}</span></li>
            <li class="gallery-content-item"><span>Downloads</span><span>${t.downloads}</span></li>
          </ul>
      </li>`).join("");i.insertAdjacentHTML("beforeend",n),y.refresh()}function h(){i.innerHTML=""}function L(){c.classList.remove("is-hidden")}function b(){c.classList.add("is-hidden")}const S=document.querySelector(".form");document.querySelector(".gallery");a.settings({pauseOnHover:!0,position:"topRight"});S.addEventListener("submit",v);function v(s){s.preventDefault();const{["search-text"]:n}=s.target.elements;h(),n.value!==""&&(L(),f(n.value).then(w).catch(t=>{a.error({message:t.message})}).finally(b))}function w(s){if(!s.hits.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(s.hits)}
//# sourceMappingURL=index.js.map
